export interface ComponentInfo {
  name: string;
  title: string;
  description: string;
  href: string;
  category?: string;
}

const componentsMap: Record<string, ComponentInfo> = {
  accordion: {
    category: "layout",
    description: "可折叠的内容区块",
    href: "/docs/components/accordion",
    name: "accordion",
    title: "Accordion",
  },
  alert: {
    category: "display",
    description: "展示重要的消息与通知",
    href: "/docs/components/alert",
    name: "alert",
    title: "Alert",
  },
  alertdialog: {
    category: "layout",
    description: "需要用户关注的关键确认对话框",
    href: "/docs/components/alert-dialog",
    name: "alertdialog",
    title: "AlertDialog",
  },
  autocomplete: {
    category: "forms",
    description: "支持搜索建议的文本输入",
    href: "/docs/components/autocomplete",
    name: "autocomplete",
    title: "Autocomplete",
  },
  avatar: {
    category: "display",
    description: "展示用户头像",
    href: "/docs/components/avatar",
    name: "avatar",
    title: "Avatar",
  },
  badge: {
    category: "display",
    description: "相对其他元素定位的小型指示器",
    href: "/docs/components/badge",
    name: "badge",
    title: "Badge",
  },
  breadcrumbs: {
    category: "navigation",
    description: "展示用户在层级结构中所处的位置",
    href: "/docs/components/breadcrumbs",
    name: "breadcrumbs",
    title: "Breadcrumbs",
  },
  button: {
    category: "forms",
    description: "供用户执行操作",
    href: "/docs/components/button",
    name: "button",
    title: "Button",
  },
  buttongroup: {
    category: "forms",
    description: "将相关的按钮组合在一起",
    href: "/docs/components/button-group",
    name: "buttongroup",
    title: "ButtonGroup",
  },
  calendar: {
    category: "date-time",
    description: "用于选择日期的交互式月份网格",
    href: "/docs/components/calendar",
    name: "calendar",
    title: "Calendar",
  },
  card: {
    category: "layout",
    description: "包含 header、body 与 footer 的内容容器",
    href: "/docs/components/card",
    name: "card",
    title: "Card",
  },
  checkbox: {
    category: "forms",
    description: "用于二元选择的输入控件",
    href: "/docs/components/checkbox",
    name: "checkbox",
    title: "Checkbox",
  },
  checkboxgroup: {
    category: "forms",
    description: "共享状态的一组复选框",
    href: "/docs/components/checkbox-group",
    name: "checkboxgroup",
    title: "CheckboxGroup",
  },
  chip: {
    category: "display",
    description: "用于标签与筛选的紧凑元素",
    href: "/docs/components/chip",
    name: "chip",
    title: "Chip",
  },
  closebutton: {
    category: "forms",
    description: "用于关闭浮层的按钮",
    href: "/docs/components/close-button",
    name: "closebutton",
    title: "CloseButton",
  },
  colorarea: {
    category: "colors",
    description: "二维取色器，用于在渐变区域中选择颜色",
    href: "/docs/components/color-area",
    name: "colorarea",
    title: "ColorArea",
  },
  colorfield: {
    category: "colors",
    description: "用于以 hex 格式输入颜色值的输入框",
    href: "/docs/components/color-field",
    name: "colorfield",
    title: "ColorField",
  },
  colorpicker: {
    category: "colors",
    description: "带 popover 的可组合颜色选择器",
    href: "/docs/components/color-picker",
    name: "colorpicker",
    title: "ColorPicker",
  },
  colorslider: {
    category: "colors",
    description: "用于调整单个颜色通道值的滑块",
    href: "/docs/components/color-slider",
    name: "colorslider",
    title: "ColorSlider",
  },
  colorswatch: {
    category: "colors",
    description: "颜色值的可视化预览",
    href: "/docs/components/color-swatch",
    name: "colorswatch",
    title: "ColorSwatch",
  },
  colorswatchpicker: {
    category: "colors",
    description: "从颜色列表中选择色块",
    href: "/docs/components/color-swatch-picker",
    name: "colorswatchpicker",
    title: "ColorSwatchPicker",
  },
  combobox: {
    category: "forms",
    description: "带可搜索下拉列表的文本输入",
    href: "/docs/components/combo-box",
    name: "combobox",
    title: "ComboBox",
  },
  datefield: {
    category: "date-time",
    description: "支持 label、description 与表单校验的日期输入字段",
    href: "/docs/components/date-field",
    name: "datefield",
    title: "DateField",
  },
  datepicker: {
    category: "date-time",
    description: "组合式日期选择器，包含日期输入触发器与日历 popover",
    href: "/docs/components/date-picker",
    name: "datepicker",
    title: "DatePicker",
  },
  daterangepicker: {
    category: "date-time",
    description: "组合式日期范围选择器，包含日期输入触发器与范围日历 popover",
    href: "/docs/components/date-range-picker",
    name: "daterangepicker",
    title: "DateRangePicker",
  },
  description: {
    category: "forms",
    description: "表单字段的辅助说明文字",
    href: "/docs/components/description",
    name: "description",
    title: "Description",
  },
  disclosure: {
    category: "layout",
    description: "单个可折叠的内容区块",
    href: "/docs/components/disclosure",
    name: "disclosure",
    title: "Disclosure",
  },
  disclosuregroup: {
    category: "layout",
    description: "一组可折叠面板",
    href: "/docs/components/disclosure-group",
    name: "disclosuregroup",
    title: "DisclosureGroup",
  },
  drawer: {
    category: "layout",
    description: "用于承载补充内容与操作的滑出式面板",
    href: "/docs/components/drawer",
    name: "drawer",
    title: "Drawer",
  },
  dropdown: {
    category: "display",
    description: "包含操作与选项的上下文菜单",
    href: "/docs/components/dropdown",
    name: "dropdown",
    title: "Dropdown",
  },
  errormessage: {
    category: "forms",
    description: "为支持表单校验的组件展示校验错误信息",
    href: "/docs/components/error-message",
    name: "errormessage",
    title: "ErrorMessage",
  },
  fielderror: {
    category: "forms",
    description: "表单字段的行内校验信息",
    href: "/docs/components/field-error",
    name: "fielderror",
    title: "FieldError",
  },
  fieldset: {
    category: "forms",
    description: "通过 legend 将相关表单控件分组",
    href: "/docs/components/fieldset",
    name: "fieldset",
    title: "Fieldset",
  },
  form: {
    category: "forms",
    description: "处理表单的校验与提交",
    href: "/docs/components/form",
    name: "form",
    title: "Form",
  },
  input: {
    category: "forms",
    description: "基于 React Aria 构建的单行文本输入",
    href: "/docs/components/input",
    name: "input",
    title: "Input",
  },
  inputgroup: {
    category: "forms",
    description: "通过 prefix 与 suffix 元素将相关的输入控件组合在一起",
    href: "/docs/components/input-group",
    name: "inputgroup",
    title: "InputGroup",
  },
  inputotp: {
    category: "forms",
    description: "一次性密码输入框",
    href: "/docs/components/input-otp",
    name: "inputotp",
    title: "InputOTP",
  },
  kbd: {
    category: "display",
    description: "键盘按键展示",
    href: "/docs/components/kbd",
    name: "kbd",
    title: "Kbd",
  },
  label: {
    category: "forms",
    description: "表单控件的无障碍标签",
    href: "/docs/components/label",
    name: "label",
    title: "Label",
  },
  link: {
    category: "navigation",
    description: "带样式的锚点链接",
    href: "/docs/components/link",
    name: "link",
    title: "Link",
  },
  listbox: {
    category: "display",
    description: "可滚动的可选项列表",
    href: "/docs/components/list-box",
    name: "list-box",
    title: "Listbox",
  },
  meter: {
    category: "feedback",
    description: "在已知范围内展示数值的指示器",
    href: "/docs/components/meter",
    name: "meter",
    title: "Meter",
  },
  modal: {
    category: "layout",
    description: "在模态浮层中展示内容",
    href: "/docs/components/modal",
    name: "modal",
    title: "Modal",
  },
  numberfield: {
    category: "forms",
    description: "带递增 / 递减按钮与表单校验的数字输入框",
    href: "/docs/components/number-field",
    name: "numberfield",
    title: "NumberField",
  },
  pagination: {
    category: "navigation",
    description: "由可组合的页码链接与控件构成的分页导航",
    href: "/docs/components/pagination",
    name: "pagination",
    title: "Pagination",
  },
  popover: {
    category: "display",
    description: "在触发器的上下文中展示内容",
    href: "/docs/components/popover",
    name: "popover",
    title: "Popover",
  },
  progressbar: {
    category: "feedback",
    description: "展示操作的确定或不确定进度",
    href: "/docs/components/progress-bar",
    name: "progressbar",
    title: "ProgressBar",
  },
  progresscircle: {
    category: "feedback",
    description: "展示操作进度的环形指示器",
    href: "/docs/components/progress-circle",
    name: "progresscircle",
    title: "ProgressCircle",
  },
  radiogroup: {
    category: "forms",
    description: "在多个选项中进行单选",
    href: "/docs/components/radio-group",
    name: "radiogroup",
    title: "RadioGroup",
  },
  rangecalendar: {
    category: "date-time",
    description: "用于选择日期范围的交互式月份网格",
    href: "/docs/components/range-calendar",
    name: "rangecalendar",
    title: "RangeCalendar",
  },
  scrollshadow: {
    category: "utilities",
    description: "通过视觉阴影提示可滚动内容的溢出",
    href: "/docs/components/scroll-shadow",
    name: "scrollshadow",
    title: "ScrollShadow",
  },
  searchfield: {
    category: "forms",
    description: "带清除按钮与搜索图标的搜索输入框",
    href: "/docs/components/search-field",
    name: "searchfield",
    title: "SearchField",
  },
  select: {
    category: "forms",
    description: "下拉选择控件",
    href: "/docs/components/select",
    name: "select",
    title: "Select",
  },
  separator: {
    category: "layout",
    description: "内容之间的视觉分隔线",
    href: "/docs/components/separator",
    name: "separator",
    title: "Separator",
  },
  skeleton: {
    category: "display",
    description: "加载占位符",
    href: "/docs/components/skeleton",
    name: "skeleton",
    title: "Skeleton",
  },
  slider: {
    category: "forms",
    description: "用于范围选择的滑块",
    href: "/docs/components/slider",
    name: "slider",
    title: "Slider",
  },
  spinner: {
    category: "display",
    description: "加载指示器",
    href: "/docs/components/spinner",
    name: "spinner",
    title: "Spinner",
  },
  surface: {
    category: "layout",
    description: "基础容器 surface",
    href: "/docs/components/surface",
    name: "surface",
    title: "Surface",
  },
  switch: {
    category: "controls",
    description: "在两种状态之间切换",
    href: "/docs/components/switch",
    name: "switch",
    title: "Switch",
  },
  table: {
    category: "display",
    description: "通过行与列展示结构化数据",
    href: "/docs/components/table",
    name: "table",
    title: "Table",
  },
  tabs: {
    category: "layout",
    description: "将内容组织为标签页视图",
    href: "/docs/components/tabs",
    name: "tabs",
    title: "Tabs",
  },
  taggroup: {
    category: "display",
    description: "可聚焦的标签列表，支持选择与删除",
    href: "/docs/components/tag-group",
    name: "taggroup",
    title: "TagGroup",
  },
  textarea: {
    category: "forms",
    description: "带焦点管理的多行文本输入",
    href: "/docs/components/text-area",
    name: "textarea",
    title: "TextArea",
  },
  textfield: {
    category: "forms",
    description: "易于组合的字段，支持 label 与表单校验",
    href: "/docs/components/text-field",
    name: "textfield",
    title: "TextField",
  },
  timefield: {
    category: "date-time",
    description: "支持 label、description 与表单校验的时间输入字段",
    href: "/docs/components/time-field",
    name: "timefield",
    title: "TimeField",
  },
  toast: {
    category: "display",
    description: "向用户展示临时通知与消息，支持自动关闭以及自定义放置位置",
    href: "/docs/components/toast",
    name: "toast",
    title: "Toast",
  },
  togglebutton: {
    category: "forms",
    description: "用于开 / 关状态的交互式切换控件",
    href: "/docs/components/toggle-button",
    name: "togglebutton",
    title: "ToggleButton",
  },
  togglebuttongroup: {
    category: "forms",
    description: "将多个 toggle button 组合成统一的控件",
    href: "/docs/components/toggle-button-group",
    name: "togglebuttongroup",
    title: "ToggleButtonGroup",
  },
  toolbar: {
    category: "layout",
    description: "用于承载交互式控件的容器，支持方向键导航",
    href: "/docs/components/toolbar",
    name: "toolbar",
    title: "Toolbar",
  },
  tooltip: {
    category: "display",
    description: "在悬停或聚焦时展示上下文信息",
    href: "/docs/components/tooltip",
    name: "tooltip",
    title: "Tooltip",
  },
};

// Define relationships between components
const componentRelationships: Record<string, string[]> = {
  accordion: ["disclosuregroup", "disclosure"],
  alert: ["closebutton", "button", "spinner", "toast"],
  alertdialog: ["button", "closebutton"],
  autocomplete: [
    "listbox",
    "popover",
    "input",
    "label",
    "fielderror",
    "form",
    "surface",
    "description",
    "avatar",
    "button",
  ],
  avatar: ["separator", "badge"],
  badge: ["avatar", "chip"],
  breadcrumbs: ["link", "separator", "tabs"],
  button: [
    "popover",
    "tooltip",
    "form",
    "alert",
    "alertdialog",
    "closebutton",
    "dropdown",
    "toast",
  ],
  buttongroup: ["button", "dropdown", "chip"],
  calendar: ["rangecalendar", "datefield", "datepicker", "timefield", "inputgroup", "form"],
  card: ["surface", "avatar", "form", "button", "link", "closebutton"],
  checkbox: ["label", "checkboxgroup", "description", "button"],
  checkboxgroup: [
    "checkbox",
    "label",
    "fieldset",
    "surface",
    "description",
    "form",
    "button",
    "fielderror",
  ],
  chip: ["avatar", "closebutton", "separator"],
  closebutton: ["alert", "alertdialog", "chip", "modal"],
  colorarea: ["colorswatch", "colorswatchpicker", "colorfield", "colorpicker"],
  colorfield: [
    "colorswatch",
    "colorswatchpicker",
    "colorpicker",
    "form",
    "label",
    "description",
    "fielderror",
  ],
  colorpicker: [
    "colorarea",
    "colorslider",
    "colorswatch",
    "colorswatchpicker",
    "colorfield",
    "popover",
  ],
  colorslider: ["colorswatch", "colorswatchpicker", "colorpicker", "slider"],
  colorswatch: ["colorswatchpicker", "colorfield", "colorarea", "colorpicker"],
  colorswatchpicker: ["colorswatch", "colorfield", "colorarea", "colorpicker"],
  combobox: [
    "listbox",
    "popover",
    "input",
    "label",
    "fielderror",
    "form",
    "surface",
    "description",
    "separator",
    "avatar",
    "spinner",
    "button",
  ],
  datefield: ["datepicker", "calendar", "label", "fielderror", "description", "form", "surface"],
  datepicker: [
    "calendar",
    "rangecalendar",
    "datefield",
    "daterangepicker",
    "timefield",
    "inputgroup",
    "form",
    "popover",
  ],
  daterangepicker: [
    "rangecalendar",
    "calendar",
    "datefield",
    "datepicker",
    "timefield",
    "inputgroup",
    "form",
    "popover",
  ],
  description: [
    "textfield",
    "input",
    "textarea",
    "checkbox",
    "radiogroup",
    "switch",
    "checkboxgroup",
    "slider",
    "select",
    "combobox",
    "numberfield",
    "datefield",
  ],
  disclosure: ["accordion", "disclosuregroup", "button"],
  disclosuregroup: ["accordion", "disclosure", "button", "separator"],
  drawer: ["modal", "button", "closebutton", "alertdialog"],
  dropdown: ["button", "popover", "separator", "listbox"],
  errormessage: ["taggroup"],
  fielderror: [
    "textfield",
    "input",
    "textarea",
    "combobox",
    "form",
    "numberfield",
    "datefield",
    "datepicker",
    "timefield",
  ],
  fieldset: ["textfield", "label", "checkboxgroup", "surface"],
  form: [
    "button",
    "fieldset",
    "textfield",
    "input",
    "textarea",
    "label",
    "fielderror",
    "checkbox",
    "checkboxgroup",
    "radiogroup",
    "switch",
    "select",
    "combobox",
    "slider",
    "inputotp",
    "numberfield",
    "datefield",
    "datepicker",
    "timefield",
  ],
  input: [
    "textfield",
    "textarea",
    "label",
    "fielderror",
    "form",
    "surface",
    "description",
    "combobox",
  ],
  inputgroup: [
    "textfield",
    "input",
    "label",
    "fielderror",
    "form",
    "surface",
    "description",
    "button",
    "chip",
    "kbd",
    "spinner",
  ],
  inputotp: ["input", "form", "surface", "button", "link", "spinner"],
  kbd: [],
  label: [
    "input",
    "textarea",
    "fieldset",
    "checkbox",
    "checkboxgroup",
    "radiogroup",
    "switch",
    "slider",
    "select",
    "combobox",
    "numberfield",
    "datefield",
    "timefield",
  ],
  link: ["breadcrumbs"],
  listbox: ["select", "combobox", "avatar", "kbd", "separator", "surface", "dropdown"],
  modal: ["button", "tooltip", "select", "avatar", "drawer"],
  numberfield: ["label", "description", "fielderror", "form", "surface", "button"],
  pagination: ["button", "link"],
  popover: ["button", "tooltip", "select", "combobox", "avatar", "dropdown"],
  radiogroup: ["fieldset", "surface", "description", "form", "button", "fielderror"],
  rangecalendar: [
    "calendar",
    "datefield",
    "datepicker",
    "daterangepicker",
    "timefield",
    "inputgroup",
    "form",
  ],
  scrollshadow: [],
  searchfield: ["label", "description", "fielderror", "form", "surface", "input", "closebutton"],
  select: [
    "listbox",
    "popover",
    "label",
    "fielderror",
    "form",
    "surface",
    "description",
    "spinner",
    "button",
    "separator",
    "avatar",
    "combobox",
  ],
  separator: [
    "card",
    "chip",
    "avatar",
    "disclosuregroup",
    "listbox",
    "select",
    "combobox",
    "dropdown",
    "breadcrumbs",
  ],
  skeleton: ["card", "avatar"],
  slider: ["label", "form", "description"],
  spinner: [],
  surface: [
    "checkboxgroup",
    "fieldset",
    "inputotp",
    "input",
    "radiogroup",
    "select",
    "combobox",
    "textfield",
    "textarea",
    "numberfield",
    "datefield",
    "datepicker",
    "timefield",
    "card",
    "listbox",
  ],
  switch: ["label", "description", "button", "form"],
  table: ["pagination", "checkbox", "chip", "avatar", "button", "spinner"],
  tabs: ["breadcrumbs"],
  taggroup: ["tag", "label", "description", "errormessage", "closebutton"],
  textarea: ["textfield", "input", "label", "fielderror", "form", "surface", "description"],
  textfield: [
    "input",
    "textarea",
    "fieldset",
    "label",
    "fielderror",
    "surface",
    "description",
    "numberfield",
    "inputgroup",
    "datefield",
  ],
  timefield: ["label", "fielderror", "description", "form", "surface"],
  toast: ["button", "alert", "closebutton", "spinner"],
  togglebutton: ["button", "switch", "checkbox", "togglebuttongroup"],
  togglebuttongroup: ["togglebutton", "buttongroup", "button"],
  toolbar: ["buttongroup", "togglebuttongroup", "separator", "button"],
  tooltip: ["button", "popover"],
};

/**
 * Get information about a specific component
 */
export function getComponentInfo(componentName: string): ComponentInfo | undefined {
  const normalizedName = componentName.toLowerCase().replace(/[-_\s]/g, "");

  return componentsMap[normalizedName];
}

/**
 * Get related components for a given component
 */
export function getRelatedComponents(componentName: string): ComponentInfo[] {
  const normalizedName = componentName.toLowerCase().replace(/[-_\s]/g, "");
  const relatedNames = componentRelationships[normalizedName] || [];

  return relatedNames
    .map((name) => componentsMap[name])
    .filter((name): name is ComponentInfo => name !== undefined);
}

/**
 * Get all components in a specific category
 */
export function getComponentsByCategory(category: string): ComponentInfo[] {
  return Object.values(componentsMap).filter((comp) => comp.category === category);
}
